apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
spec:
  template:
    spec:
      containers:
      - name: django-migrate
        image: django_app
        envFrom:
          - configMapRef:
              name: max-config
        command:
          - python
        args:
          - manage.py
          - migrate
        imagePullPolicy: Never
      restartPolicy: Never
  backoffLimit: 3
