apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
spec:
  template:
    spec:
      containers:
      - name: django-migrate
        image: django_app
        envFrom:
          - configMapRef:
              name: max-config
        command: ["/bin/sh", "-c", "/usr/local/bin/python /code/manage.py migrate"]
        imagePullPolicy: Never
      restartPolicy: Never
  backoffLimit: 4
