apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-data-pvc
  namespace: default
  labels:
    app: pg-data-pvc
spec:
  storageClassName: csi-disk
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi